//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ohjelmistoprojekti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HenkilonOsaamiset
    {
        public int HenkilonOsaamisID { get; set; }
        public Nullable<int> OsaamisaiheID { get; set; }
        public Nullable<int> HenkiloID { get; set; }
        public Nullable<int> Osaamistaso { get; set; }
    
        public virtual Henkilot Henkilot { get; set; }
        public virtual Osaamisaiheet Osaamisaiheet { get; set; }
    }
}
