//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ohjelmistoprojekti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osaamisaiheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Osaamisaiheet()
        {
            this.HenkilonOsaamiset = new HashSet<HenkilonOsaamiset>();
        }
    
        public int OsaamisaiheID { get; set; }
        public string Kuvaus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HenkilonOsaamiset> HenkilonOsaamiset { get; set; }
    }
}
